### ISSUE TITLE
Support working behind an SSL-terminating proxy

### ISSUE THREAD

**Issue by d5ve** [ap/Plack-Middleware-RedirectSSL#2]
This plugin currently checks `$env->{'psgi.url_scheme'}` to work out whether the current request is over http, or https.

This is incorrect for a webserver running behind an SSL-terminating proxy.

If the plugin also looked for standard headers such as `X-Forwarded-Proto` and Microsoft's `Front-End-Https`, then it could work behind a proxy.

Would you be interested in a patch for this behaviour?

Cheers,

Dave

**Comment by ap** [comment]
At a glance I think you’re wrong. I believe you want to put Plack::Middleware::ReverseProxy in front of this middleware, and *not* patch this middleware.

The issue with your proposal is that `X-Forwarded-Proto` and friends should be heeded only if the app is actually running behind a reverse proxy – but *not* if it’s running directly exposed to the internet, because then the origin remote client could send these headers and fool the app about what’s going on.

Since the app cannot know whether it is running behind a reverse proxy, it’s up to you to enable ::ReverseProxy or not, according to your local deployment situation.

(Am I missing something?)

**Comment by d5ve** [comment]
I'd not seen Plack::Middleware::ReverseProxy, thanks. I'll try that and see if it works for my usecase.

**Comment by d5ve** [comment]
Plack::Middleware::ReverseProxy and Plack::Middleware::RedirectSSL together do exactly what I needed. Thanks again.
